//using LightBuzz.Kinect4Azure;
//using System.Collections.Generic;
//using UnityEngine;

//namespace TrackManager.BodyTracking
//{
//    internal static class AvateeringConstants
//    {
//        //
//        // Summary:
//        //     Joints that reflect to unity joints
//        public static readonly Dictionary<JointType, HumanBodyBones> LightBuzzCrossAnimatorBones = new Dictionary<JointType, HumanBodyBones>
//        {
//            {
//                JointType.Head,
//                HumanBodyBones.Head
//            },
//            {
//                JointType.Neck,
//                HumanBodyBones.Neck
//            },
//            {
//                JointType.SpineChest,
//                HumanBodyBones.Chest
//            },
//            {
//                JointType.SpineNaval,
//                HumanBodyBones.Spine
//            },
//            {
//                JointType.Pelvis,
//                HumanBodyBones.Hips
//            },
//            {
//                JointType.ClavicleLeft,
//                HumanBodyBones.LeftShoulder
//            },
//            {
//                JointType.ShoulderLeft,
//                HumanBodyBones.LeftUpperArm
//            },
//            {
//                JointType.ElbowLeft,
//                HumanBodyBones.LeftLowerArm
//            },
//            {
//                JointType.WristLeft,
//                HumanBodyBones.LeftHand
//            },
//            {
//                JointType.ThumbLeft,
//                HumanBodyBones.LeftThumbDistal
//            },
//            {
//                JointType.HandtipLeft,
//                HumanBodyBones.LeftMiddleDistal
//            },
//            {
//                JointType.ClavicleRight,
//                HumanBodyBones.RightShoulder
//            },
//            {
//                JointType.ShoulderRight,
//                HumanBodyBones.RightUpperArm
//            },
//            {
//                JointType.ElbowRight,
//                HumanBodyBones.RightLowerArm
//            },
//            {
//                JointType.WristRight,
//                HumanBodyBones.RightHand
//            },
//            {
//                JointType.ThumbRight,
//                HumanBodyBones.RightThumbDistal
//            },
//            {
//                JointType.HandtipRight,
//                HumanBodyBones.RightMiddleDistal
//            },
//            {
//                JointType.HipLeft,
//                HumanBodyBones.LeftUpperLeg
//            },
//            {
//                JointType.KneeLeft,
//                HumanBodyBones.LeftLowerLeg
//            },
//            {
//                JointType.AnkleLeft,
//                HumanBodyBones.LeftFoot
//            },
//            {
//                JointType.FootLeft,
//                HumanBodyBones.LeftToes
//            },
//            {
//                JointType.HipRight,
//                HumanBodyBones.RightUpperLeg
//            },
//            {
//                JointType.KneeRight,
//                HumanBodyBones.RightLowerLeg
//            },
//            {
//                JointType.AnkleRight,
//                HumanBodyBones.RightFoot
//            },
//            {
//                JointType.FootRight,
//                HumanBodyBones.RightToes
//            }
//        };

//        //
//        // Summary:
//        //     Maps the human joints to their mirrored equivalents.
//        public static readonly Dictionary<JointType, JointType> JointTypeToFlippedJointType = new Dictionary<JointType, JointType>
//        {
//            {
//                JointType.Pelvis,
//                JointType.Pelvis
//            },
//            {
//                JointType.SpineNaval,
//                JointType.SpineNaval
//            },
//            {
//                JointType.SpineChest,
//                JointType.SpineChest
//            },
//            {
//                JointType.Neck,
//                JointType.Neck
//            },
//            {
//                JointType.ClavicleLeft,
//                JointType.ClavicleRight
//            },
//            {
//                JointType.ShoulderLeft,
//                JointType.ShoulderRight
//            },
//            {
//                JointType.ElbowLeft,
//                JointType.ElbowRight
//            },
//            {
//                JointType.WristLeft,
//                JointType.WristRight
//            },
//            {
//                JointType.HandLeft,
//                JointType.HandRight
//            },
//            {
//                JointType.HandtipLeft,
//                JointType.HandtipRight
//            },
//            {
//                JointType.ThumbLeft,
//                JointType.ThumbRight
//            },
//            {
//                JointType.ClavicleRight,
//                JointType.ClavicleLeft
//            },
//            {
//                JointType.ShoulderRight,
//                JointType.ShoulderLeft
//            },
//            {
//                JointType.ElbowRight,
//                JointType.ElbowLeft
//            },
//            {
//                JointType.WristRight,
//                JointType.WristLeft
//            },
//            {
//                JointType.HandRight,
//                JointType.HandLeft
//            },
//            {
//                JointType.HandtipRight,
//                JointType.HandtipLeft
//            },
//            {
//                JointType.ThumbRight,
//                JointType.ThumbLeft
//            },
//            {
//                JointType.HipLeft,
//                JointType.HipRight
//            },
//            {
//                JointType.KneeLeft,
//                JointType.KneeRight
//            },
//            {
//                JointType.AnkleLeft,
//                JointType.AnkleRight
//            },
//            {
//                JointType.FootLeft,
//                JointType.FootRight
//            },
//            {
//                JointType.HipRight,
//                JointType.HipLeft
//            },
//            {
//                JointType.KneeRight,
//                JointType.KneeLeft
//            },
//            {
//                JointType.AnkleRight,
//                JointType.AnkleLeft
//            },
//            {
//                JointType.FootRight,
//                JointType.FootLeft
//            },
//            {
//                JointType.Head,
//                JointType.Head
//            },
//            {
//                JointType.Nose,
//                JointType.Nose
//            },
//            {
//                JointType.EyeLeft,
//                JointType.EyeRight
//            },
//            {
//                JointType.EarLeft,
//                JointType.EarRight
//            },
//            {
//                JointType.EyeRight,
//                JointType.EyeLeft
//            },
//            {
//                JointType.EarRight,
//                JointType.EarLeft
//            }
//        };

//        public static readonly Dictionary<JointType, JointType> LinkedJoints = new Dictionary<JointType, JointType>
//        {
//            {
//                JointType.ClavicleLeft,
//                JointType.ShoulderLeft
//            },
//            {
//                JointType.ShoulderLeft,
//                JointType.ElbowLeft
//            },
//            {
//                JointType.ElbowLeft,
//                JointType.WristLeft
//            },
//            {
//                JointType.ClavicleRight,
//                JointType.ShoulderRight
//            },
//            {
//                JointType.ShoulderRight,
//                JointType.ElbowRight
//            },
//            {
//                JointType.ElbowRight,
//                JointType.WristRight
//            },
//            {
//                JointType.HipLeft,
//                JointType.KneeLeft
//            },
//            {
//                JointType.KneeLeft,
//                JointType.AnkleLeft
//            },
//            {
//                JointType.AnkleLeft,
//                JointType.FootLeft
//            },
//            {
//                JointType.HipRight,
//                JointType.KneeRight
//            },
//            {
//                JointType.KneeRight,
//                JointType.AnkleRight
//            },
//            {
//                JointType.AnkleRight,
//                JointType.FootRight
//            }
//        };
//    }
//}